/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;
/**
 *
 * @author Jimmy Ramirez
 */
public class CaluladoraCientifica extends javax.swing.JFrame {
  //Declaramos los atributos
    private boolean igual,inicio = true,operacion1,operacion2;
    private double a,b,c,cos,acos,sin,asin,tan,atan,memoria = 0,resultado,valor1,valor2;
    private String cadena,funciones,tipoOperaciones;
    

          
    public CaluladoraCientifica() {
        initComponents();
   this.setLocationRelativeTo(null);
   Label2_Memoría.setVisible(igual);
   // this.getContentPane().setBackgroud(color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        RadioButton_Sexages = new javax.swing.JRadioButton();
        RadioButton_Radianes = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        Label2_Memoría = new javax.swing.JLabel();
        txtvisor_principal = new javax.swing.JTextField();
        txtvisor_previo = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        boton_tan = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        boton_cos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        boton_sin = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButtonN7 = new javax.swing.JButton();
        jButtonN4 = new javax.swing.JButton();
        jButtonN1 = new javax.swing.JButton();
        jButtonN0 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButtonN8 = new javax.swing.JButton();
        jButtonN5 = new javax.swing.JButton();
        jButtonN2 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButtonN9 = new javax.swing.JButton();
        jButtonN6 = new javax.swing.JButton();
        jButtonN3 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jButton44.setBackground(new java.awt.Color(255, 255, 102));
        jButton44.setForeground(new java.awt.Color(0, 0, 255));
        jButton44.setText("√");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });

        jButton45.setBackground(new java.awt.Color(255, 255, 102));
        jButton45.setForeground(new java.awt.Color(0, 0, 255));
        jButton45.setText("%");
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });

        jButton46.setBackground(new java.awt.Color(255, 255, 102));
        jButton46.setForeground(new java.awt.Color(0, 0, 255));
        jButton46.setText("1/x");
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });

        jButton47.setBackground(new java.awt.Color(255, 255, 102));
        jButton47.setForeground(new java.awt.Color(0, 0, 255));
        jButton47.setText("=");
        jButton47.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });

        RadioButton_Sexages.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(RadioButton_Sexages);
        RadioButton_Sexages.setForeground(new java.awt.Color(0, 0, 255));
        RadioButton_Sexages.setSelected(true);
        RadioButton_Sexages.setText("Sexages");
        RadioButton_Sexages.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        RadioButton_Radianes.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(RadioButton_Radianes);
        RadioButton_Radianes.setForeground(new java.awt.Color(0, 0, 255));
        RadioButton_Radianes.setText("Radianes.");
        RadioButton_Radianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_RadianesActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label2_Memoría.setText("M");
        jPanel3.add(Label2_Memoría, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 20, -1));

        txtvisor_principal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtvisor_principal.setForeground(new java.awt.Color(0, 0, 204));
        txtvisor_principal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtvisor_principal.setText("0");
        txtvisor_principal.setBorder(null);
        txtvisor_principal.setFocusable(false);
        jPanel3.add(txtvisor_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 470, 50));

        txtvisor_previo.setForeground(new java.awt.Color(0, 0, 153));
        txtvisor_previo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtvisor_previo.setBorder(null);
        txtvisor_previo.setFocusable(false);
        txtvisor_previo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvisor_previoActionPerformed(evt);
            }
        });
        jPanel3.add(txtvisor_previo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 20));

        jButton9.setBackground(new java.awt.Color(255, 255, 102));
        jButton9.setForeground(new java.awt.Color(0, 0, 255));
        jButton9.setText("X^-1");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 255, 102));
        jButton10.setForeground(new java.awt.Color(0, 0, 255));
        jButton10.setText("y√ x");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 255, 102));
        jButton11.setForeground(new java.awt.Color(0, 0, 255));
        jButton11.setText("3√ x");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 255, 102));
        jButton12.setForeground(new java.awt.Color(0, 0, 255));
        jButton12.setText("EXP");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        boton_tan.setBackground(new java.awt.Color(255, 255, 102));
        boton_tan.setForeground(new java.awt.Color(0, 0, 255));
        boton_tan.setText("tan");
        boton_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_tanActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(255, 255, 102));
        jButton14.setForeground(new java.awt.Color(0, 0, 255));
        jButton14.setText("tan-1");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(255, 255, 102));
        jButton15.setForeground(new java.awt.Color(0, 0, 255));
        jButton15.setText("X^y");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(255, 255, 102));
        jButton16.setForeground(new java.awt.Color(0, 0, 255));
        jButton16.setText("X^3");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(255, 255, 102));
        jButton17.setForeground(new java.awt.Color(0, 0, 255));
        jButton17.setText("X^2");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(255, 255, 102));
        jButton18.setForeground(new java.awt.Color(0, 0, 255));
        jButton18.setText("log");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        boton_cos.setBackground(new java.awt.Color(255, 255, 102));
        boton_cos.setForeground(new java.awt.Color(0, 0, 255));
        boton_cos.setText(" cos");
        boton_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cosActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("cos-1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 102));
        jButton3.setForeground(new java.awt.Color(0, 0, 255));
        jButton3.setText("pi(n)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 102));
        jButton4.setForeground(new java.awt.Color(0, 0, 255));
        jButton4.setText("e");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 102));
        jButton5.setForeground(new java.awt.Color(0, 0, 255));
        jButton5.setText("n!");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 102));
        jButton6.setForeground(new java.awt.Color(0, 0, 255));
        jButton6.setText("10^x");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        boton_sin.setBackground(new java.awt.Color(255, 255, 102));
        boton_sin.setForeground(new java.awt.Color(0, 0, 255));
        boton_sin.setText("sin");
        boton_sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_sinActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 102));
        jButton8.setForeground(new java.awt.Color(0, 0, 255));
        jButton8.setText("sin-1");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(255, 255, 102));
        jButton19.setForeground(new java.awt.Color(0, 0, 255));
        jButton19.setText("MC");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(255, 255, 102));
        jButton20.setForeground(new java.awt.Color(0, 0, 255));
        jButton20.setText("<--");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButtonN7.setBackground(new java.awt.Color(204, 204, 255));
        jButtonN7.setForeground(new java.awt.Color(51, 0, 51));
        jButtonN7.setText("7");
        jButtonN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN7ActionPerformed(evt);
            }
        });

        jButtonN4.setBackground(new java.awt.Color(204, 204, 255));
        jButtonN4.setForeground(new java.awt.Color(51, 0, 51));
        jButtonN4.setText("4");
        jButtonN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN4ActionPerformed(evt);
            }
        });

        jButtonN1.setBackground(new java.awt.Color(204, 204, 255));
        jButtonN1.setForeground(new java.awt.Color(51, 0, 51));
        jButtonN1.setText("1");
        jButtonN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN1ActionPerformed(evt);
            }
        });

        jButtonN0.setBackground(new java.awt.Color(204, 204, 255));
        jButtonN0.setForeground(new java.awt.Color(51, 0, 51));
        jButtonN0.setText("0");
        jButtonN0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN0ActionPerformed(evt);
            }
        });

        jButton25.setBackground(new java.awt.Color(255, 255, 102));
        jButton25.setForeground(new java.awt.Color(0, 0, 255));
        jButton25.setText("MR");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setBackground(new java.awt.Color(255, 255, 102));
        jButton26.setForeground(new java.awt.Color(204, 0, 0));
        jButton26.setText("CE");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButtonN8.setBackground(new java.awt.Color(204, 204, 255));
        jButtonN8.setForeground(new java.awt.Color(51, 0, 51));
        jButtonN8.setText("8");
        jButtonN8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN8ActionPerformed(evt);
            }
        });

        jButtonN5.setBackground(new java.awt.Color(204, 204, 255));
        jButtonN5.setForeground(new java.awt.Color(51, 0, 51));
        jButtonN5.setText("5");
        jButtonN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN5ActionPerformed(evt);
            }
        });

        jButtonN2.setBackground(new java.awt.Color(204, 204, 255));
        jButtonN2.setForeground(new java.awt.Color(51, 0, 51));
        jButtonN2.setText("2");
        jButtonN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN2ActionPerformed(evt);
            }
        });

        jButton30.setBackground(new java.awt.Color(204, 204, 255));
        jButton30.setForeground(new java.awt.Color(51, 0, 51));
        jButton30.setText(".");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jButton31.setBackground(new java.awt.Color(255, 255, 102));
        jButton31.setForeground(new java.awt.Color(0, 0, 255));
        jButton31.setText("MS");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton32.setBackground(new java.awt.Color(255, 255, 102));
        jButton32.setForeground(new java.awt.Color(204, 0, 0));
        jButton32.setText("C");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        jButtonN9.setBackground(new java.awt.Color(204, 204, 255));
        jButtonN9.setForeground(new java.awt.Color(51, 0, 51));
        jButtonN9.setText("9");
        jButtonN9.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonN9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN9ActionPerformed(evt);
            }
        });

        jButtonN6.setBackground(new java.awt.Color(204, 204, 255));
        jButtonN6.setForeground(new java.awt.Color(51, 0, 51));
        jButtonN6.setText("6");
        jButtonN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN6ActionPerformed(evt);
            }
        });

        jButtonN3.setBackground(new java.awt.Color(204, 204, 255));
        jButtonN3.setForeground(new java.awt.Color(51, 0, 51));
        jButtonN3.setText("3");
        jButtonN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN3ActionPerformed(evt);
            }
        });

        jButton37.setBackground(new java.awt.Color(255, 255, 102));
        jButton37.setForeground(new java.awt.Color(0, 0, 255));
        jButton37.setText("M+");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });

        jButton38.setBackground(new java.awt.Color(255, 255, 102));
        jButton38.setForeground(new java.awt.Color(0, 0, 255));
        jButton38.setText("±");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });

        jButton39.setBackground(new java.awt.Color(255, 255, 102));
        jButton39.setForeground(new java.awt.Color(0, 0, 255));
        jButton39.setText("/");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });

        jButton40.setBackground(new java.awt.Color(255, 255, 102));
        jButton40.setForeground(new java.awt.Color(0, 0, 255));
        jButton40.setText("*");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });

        jButton41.setBackground(new java.awt.Color(255, 255, 102));
        jButton41.setForeground(new java.awt.Color(0, 0, 255));
        jButton41.setText("-");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });

        jButton42.setBackground(new java.awt.Color(255, 255, 102));
        jButton42.setForeground(new java.awt.Color(0, 0, 255));
        jButton42.setText("+");
        jButton42.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });

        jButton43.setBackground(new java.awt.Color(255, 255, 102));
        jButton43.setForeground(new java.awt.Color(0, 0, 255));
        jButton43.setText("M-");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton_cos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton_sin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boton_tan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonN4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonN7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton20)
                                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton25)
                                    .addComponent(jButtonN8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonN5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonN9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonN6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonN1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonN2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonN0, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonN3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton37)
                            .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton46)
                            .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RadioButton_Sexages)
                        .addGap(10, 10, 10)
                        .addComponent(RadioButton_Radianes))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButton_Sexages)
                    .addComponent(RadioButton_Radianes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(boton_cos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(boton_sin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11)
                            .addComponent(jButton17)
                            .addComponent(jButtonN1)
                            .addComponent(jButtonN2)
                            .addComponent(jButtonN3)
                            .addComponent(jButton41))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton_tan)
                            .addComponent(jButton19)
                            .addComponent(jButton25)
                            .addComponent(jButton31)
                            .addComponent(jButton37)
                            .addComponent(jButton43))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton14)
                            .addComponent(jButton20)
                            .addComponent(jButton26)
                            .addComponent(jButton32)
                            .addComponent(jButton38)
                            .addComponent(jButton44))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton15)
                            .addComponent(jButtonN7)
                            .addComponent(jButtonN8)
                            .addComponent(jButtonN9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton39)
                            .addComponent(jButton45))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton16)
                            .addComponent(jButtonN4)
                            .addComponent(jButtonN5)
                            .addComponent(jButtonN6)
                            .addComponent(jButton40)
                            .addComponent(jButton46))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton18)
                                    .addComponent(jButtonN0)
                                    .addComponent(jButton30)
                                    .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     //Boton que realiza la operacion cambio en signo
    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
   double nu1 = 0,nu2,nu3;
   nu2 = Double.parseDouble(txtvisor_principal.getText());
   nu3 = nu1-nu2;
   txtvisor_principal.setText(nu3 + " ");
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButtonN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN1ActionPerformed
        // condicion para la variable inicio
    if(inicio == true){
            txtvisor_principal.setText("");
        txtvisor_principal.setText("1");
        inicio = false;
    }else{
    txtvisor_principal.setText(txtvisor_principal.getText()+"1");
   }    
    }//GEN-LAST:event_jButtonN1ActionPerformed

    private void jButtonN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN2ActionPerformed
        // TODO add your handling code here:
           if(inicio == true){
            txtvisor_principal.setText("null");
        txtvisor_principal.setText("2");
        inicio = false;
    }else{
    txtvisor_principal.setText(txtvisor_principal.getText()+"2");
   }    
 
    }//GEN-LAST:event_jButtonN2ActionPerformed

    private void jButtonN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN3ActionPerformed
        // TODO add your handling code here:
           if(inicio == true){
            txtvisor_principal.setText("");
        txtvisor_principal.setText("3");
        inicio = false;
    }else{
    txtvisor_principal.setText(txtvisor_principal.getText()+"3");
   }    
                

    }//GEN-LAST:event_jButtonN3ActionPerformed

    private void jButtonN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN4ActionPerformed
        // TODO add your handling code here:
           if(inicio == true){
            txtvisor_principal.setText("");
        txtvisor_principal.setText("4");
        inicio = false;
    }else{
    txtvisor_principal.setText(txtvisor_principal.getText()+"4");
   }    
                

    }//GEN-LAST:event_jButtonN4ActionPerformed

    private void jButtonN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN5ActionPerformed
        // TODO add your handling code here:
           if(inicio == true){
            txtvisor_principal.setText("");
        txtvisor_principal.setText("5");
        inicio = false;
    }else{
    txtvisor_principal.setText(txtvisor_principal.getText()+"5");
   }    
                

    }//GEN-LAST:event_jButtonN5ActionPerformed

    private void jButtonN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN6ActionPerformed
        // TODO add your handling code here:
           if(inicio == true){
            txtvisor_principal.setText("");
        txtvisor_principal.setText("6");
        inicio = false;
    }else{
    txtvisor_principal.setText(txtvisor_principal.getText()+"6");
   }    
               

    }//GEN-LAST:event_jButtonN6ActionPerformed

    private void jButtonN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN7ActionPerformed
        // TODO add your handling code here:
                  if(inicio == true){
            txtvisor_principal.setText("");
        txtvisor_principal.setText("7");
        inicio = false;
    }else{
    txtvisor_principal.setText(txtvisor_principal.getText()+"7");
   }    

    }//GEN-LAST:event_jButtonN7ActionPerformed

    private void jButtonN8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN8ActionPerformed
        // TODO add your handling code here:
               if(inicio == true){
            txtvisor_principal.setText("");
        txtvisor_principal.setText("8");
        inicio = false;
    }else{
    txtvisor_principal.setText(txtvisor_principal.getText()+"8");
   }    

    }//GEN-LAST:event_jButtonN8ActionPerformed

    private void jButtonN9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN9ActionPerformed
        // TODO add your handling code here:
           if(inicio == true){
            txtvisor_principal.setText("");
        txtvisor_principal.setText("9");
        inicio = false;
    }else{
    txtvisor_principal.setText(txtvisor_principal.getText()+"9");
   }    

               

    }//GEN-LAST:event_jButtonN9ActionPerformed

    private void jButtonN0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN0ActionPerformed
        // TODO add your handling code here:
                  if(inicio == true){
            txtvisor_principal.setText("");
        txtvisor_principal.setText("0");
        inicio = false;
    }else{
    txtvisor_principal.setText(txtvisor_principal.getText()+"0");
   }    

    }//GEN-LAST:event_jButtonN0ActionPerformed

    private void txtvisor_previoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvisor_previoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvisor_previoActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // Contains devuelve un valor que indica si el punto especificado aparece dentro
     if (txtvisor_principal.getText().contains(".")){
        
    }else{
     txtvisor_principal.setText(txtvisor_principal.getText()+".");
                   inicio = false;
            }
    }//GEN-LAST:event_jButton30ActionPerformed
     // botón de la función de suma
    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        igual = true;
        inicio =true;
        //Condicion para la variable opereacion1
        if (operacion1 = true){
        valor1 = Double.parseDouble(txtvisor_principal.getText());
        txtvisor_previo.setText(txtvisor_principal.getText()+"+");
        operacion1 = false;
    }else{
        //Condicion para la variable opereacion2
        if (operacion2 = true) {
        valor2 = Double.parseDouble(txtvisor_principal.getText());
        txtvisor_previo.setText(txtvisor_principal.getText()+"+");
        operacion2 = false;
    }else{
    txtvisor_previo.setText(txtvisor_principal.getText()+"+");
             operaciones(resultado,valor2);
            }                
         }
         tipoOperaciones = "+";
           
    }//GEN-LAST:event_jButton42ActionPerformed
// botón de la función de resta
    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:
          igual = true;
        inicio =true;
        //Condicion para la variable opereacion1
        if (operacion1 = true){
        valor1 = Double.parseDouble(txtvisor_principal.getText());
        txtvisor_previo.setText(txtvisor_principal.getText()+"-");
        operacion1 = false;
    }else{
        //Condicion para la variable opereacion2
        if (operacion2 = true) {
        valor2 = Double.parseDouble(txtvisor_principal.getText());
        txtvisor_previo.setText(txtvisor_principal.getText()+"-");
        operacion2 = false;
    }else{
    txtvisor_previo.setText(txtvisor_principal.getText()+"-");
             operaciones(resultado,valor2);
            }                
         }
         tipoOperaciones = "-";
           
    }//GEN-LAST:event_jButton41ActionPerformed
// botón de la función de multiplicar
    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        // TODO add your handling code here:
          igual = true;
        inicio =true;
        //Condicion para la variable opereacion1
        if (operacion1 = true){
        valor1 = Double.parseDouble(txtvisor_principal.getText());
        txtvisor_previo.setText(txtvisor_principal.getText()+"*");
        operacion1 = false;
    }else{
        //Condicion para la variable opereacion2
        if (operacion2 = true) {
        valor2 = Double.parseDouble(txtvisor_principal.getText());
        txtvisor_previo.setText(txtvisor_principal.getText()+"*");
        operacion2 = false;
    }else{
    txtvisor_previo.setText(txtvisor_principal.getText()+"*");
             operaciones(resultado,valor2);
            }                
         }
         tipoOperaciones = "*";
           
    }//GEN-LAST:event_jButton40ActionPerformed
// botón de la función de división
    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        // TODO add your handling code here:
          igual = true;
        inicio =true;
        //Condicion para la variable opereacion1
        if (operacion1 = true){
        valor1 = Double.parseDouble(txtvisor_principal.getText());
        txtvisor_previo.setText(txtvisor_principal.getText()+"/");
        operacion1 = false;
    }else{
        //Condicion para la variable opereacion2
        if (operacion2 = true) {
        valor2 = Double.parseDouble(txtvisor_principal.getText());
        txtvisor_previo.setText(txtvisor_principal.getText()+"/");
        operacion2 = false;
    }else{
    txtvisor_previo.setText(txtvisor_principal.getText()+"/");
             operaciones(resultado,valor2);
            }                
         }
         tipoOperaciones = "/";
           
    }//GEN-LAST:event_jButton39ActionPerformed
 //Método con las operaciones de suma resta multiplicación y divión
    private void operaciones(double valor1, double valor2){
//Switch que evalua la variables tipoOperaciones
switch(tipoOperaciones){
     // Case con las funciones de suma
    case"+":
        resultado = valor1 + valor2;
        txtvisor_principal.setText(resultado + "");
        valor1 = Double.parseDouble(txtvisor_principal.getText());
       break;
    // Case con las funciones de resta
    case"-":
        resultado = valor1 - valor2;
        txtvisor_principal.setText(resultado + "");
        valor1 = Double.parseDouble(txtvisor_principal.getText());
       break;
        // Case con las funciones de multiplicar
    case"*":
        resultado = valor1 * valor2;
        txtvisor_principal.setText(resultado + "");
        valor1 = Double.parseDouble(txtvisor_principal.getText());
       break;
        // Case con las funciones de división
    case"/":
          if (valor2 == 0) {
          txtvisor_principal.setText("Eroor");
          break;
          }else{
          resultado = valor1 / valor2;
          txtvisor_principal.setText(resultado + "");
          valor1 = Double.parseDouble(txtvisor_principal.getText());
          break;
            }
            //Case de la función que saca la potencia de un número
                case    "potencia":
              resultado = Math.pow(valor1,valor2);
              txtvisor_principal.setText(resultado +" ");
              break;
              
              //Case de la funcion que saca la raiz x de un numero
                case "raizx":
                    if (valor2<=0){
                        txtvisor_principal.setText("Error");
                        break;
                    }else{
                        txtvisor_previo.setText(valor2 +"yroot");
                        a = 1;
                        c =a/valor2;
                        txtvisor_principal.setText(Math.pow(valor1,c)+ " ");
                        break;
                        
                        
                        
                    }
}
    }
// botón de la función de igual   
    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
 inicio = true;
 operacion1 = true;
 if (igual = true){
     if(tipoOperaciones == null){
         
     }else{
         valor2 = Double.parseDouble(txtvisor_principal.getText());
         txtvisor_previo.setText(txtvisor_previo.getText()+txtvisor_principal.getText());
         operaciones(valor1,valor2);
         igual = false;
     
       }
       }else{
     txtvisor_previo.setText("");
     operaciones(valor1,valor2);
 }
    }//GEN-LAST:event_jButton47ActionPerformed
//Botón con la función de RAIZ CUADRADA
    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
   valor1 = Double.parseDouble(txtvisor_principal.getText());
   if (valor1 >=0){
     txtvisor_previo.setText("sqrt("+valor1+" ) ");
    txtvisor_principal.setText(Math.sqrt(valor1)+" ");
    }else{
     txtvisor_principal.setText("Erros");
}
   
    }//GEN-LAST:event_jButton44ActionPerformed
//boton con la funcion c
    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        txtvisor_principal.setText("0");
         txtvisor_previo.setText("");
         inicio = true;
         funciones = "";
         operacion1 = true;
         operacion2 = true;
         igual =true;
         valor1= 0;
         valor2 =0;
         resultado = 0;
    }//GEN-LAST:event_jButton32ActionPerformed
  //boton con la funcion de CE
    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        txtvisor_principal.setText("0");
        txtvisor_previo.setText("");
        inicio = true;
        funciones = "";
        
    }//GEN-LAST:event_jButton26ActionPerformed
// boton con la funcion de RETROCEDER
    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
          if (txtvisor_principal.getText().length()>0) {
              txtvisor_principal.setText(txtvisor_principal.getText().substring(0,txtvisor_principal.getText().length()-1));
              if (txtvisor_principal.getText().length() == 0) {
                  txtvisor_principal.setText("0");
                  inicio = true;
             
              }
          }
    }//GEN-LAST:event_jButton20ActionPerformed
      // Boton con la funcion de PORCENTAJE
    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
               valor2= Double.parseDouble(txtvisor_principal.getText());
               txtvisor_previo.setText(txtvisor_previo.getText()+txtvisor_principal.getText());
          txtvisor_principal.setText((valor1*valor2)/100 +" ");
            igual = true;
       
    }//GEN-LAST:event_jButton45ActionPerformed
   // Boton que raliza la operacion inversa 1/x
    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
  valor1 = Double.parseDouble(txtvisor_principal.getText());
  txtvisor_previo.setText("reciproc(" + valor1 +" )");
  txtvisor_principal.setText(1/valor1 + " ");
    }//GEN-LAST:event_jButton46ActionPerformed
 //metodo trigonomitria
    public void Trigonometria(){
        //condicion que evaluea el RadioButton si es seleccionado
         if (RadioButton_Sexages.isSelected()) {
           //Switch que evelua la variable funciones
           switch(funciones){
           //Seno
           case "sin":
           valor1 = Double.parseDouble(txtvisor_principal.getText());
           txtvisor_previo.setText("sin( " +valor1+")");
           sin = Math.sin(Math.PI*(valor1)/180);
           txtvisor_principal.setText(sin+"  ");
         break;
           //Seno invesor
           case "asin":
           valor1 = Double.parseDouble(txtvisor_principal.getText());
           txtvisor_previo.setText("asin( " +valor1+")");
           asin = Math.asin(valor1)*180/Math.PI;
           txtvisor_principal.setText(asin+"  ");
         break;
           //coseno
           case "cos":
           valor1 = Double.parseDouble(txtvisor_principal.getText());
           txtvisor_previo.setText("cos( " +valor1+")");
           cos = Math.cos(Math.PI*(valor1)/180);
           txtvisor_principal.setText(cos+"  ");
         break;
           //coseno invesor
           case "acos":
           valor1 = Double.parseDouble(txtvisor_principal.getText());
           txtvisor_previo.setText("acos( " +valor1+")");
          acos = Math.acos(valor1)*180/Math.PI;
           txtvisor_principal.setText(acos+"  ");
         break;
           //Tangente
           case "tan":
           valor1 = Double.parseDouble(txtvisor_principal.getText());
           txtvisor_previo.setText("tan( " +valor1+")");
           tan = Math.tan(Math.PI*(valor1)/180);
           txtvisor_principal.setText(tan+"  ");
         break;
           //Tangente invesor
           case "atan":
           valor1 = Double.parseDouble(txtvisor_principal.getText());
           txtvisor_previo.setText("atan( " +valor1+")");
           atan = Math.atan(valor1)*180/Math.PI;
           txtvisor_principal.setText(atan+"  ");
         break;
         }
       }else{
            //condicion que evaluea el RadioButton si es seleccionado
         if (RadioButton_Radianes.isSelected()) {
           //Switch que evelua la variable funciones
           switch(funciones){
           //Seno
           case "sin":
           valor1 = Double.parseDouble(txtvisor_principal.getText());
           txtvisor_previo.setText("sinr( " +valor1+")");
           sin = Math.sin(valor1);
           txtvisor_principal.setText(sin+"  ");
         break;
           //Seno invesor
           case "asin":
           valor1 = Double.parseDouble(txtvisor_principal.getText());
           txtvisor_previo.setText("asinr( " +valor1+")");
           asin = Math.asin(valor1);
           txtvisor_principal.setText(asin+"  ");
         break;
           //coseno
           case "cos":
           valor1 = Double.parseDouble(txtvisor_principal.getText());
           txtvisor_previo.setText("cosr( " +valor1+")");
           cos = Math.cos(valor1);
           txtvisor_principal.setText(cos+"  ");
         break;
           //coseno invesor
           case "acos":
           valor1 = Double.parseDouble(txtvisor_principal.getText());
           txtvisor_previo.setText("acosr( " +valor1+")");
          acos = Math.acos(valor1);
           txtvisor_principal.setText(acos+"  ");
         break;
           //Tangente
           case "tan":
           valor1 = Double.parseDouble(txtvisor_principal.getText());
           txtvisor_previo.setText("tanr( " +valor1+")");
           tan = Math.tan(valor1);
           txtvisor_principal.setText(tan+"  ");
         break;
           //Tangente invesor
           case "atan":
           valor1 = Double.parseDouble(txtvisor_principal.getText());
           txtvisor_previo.setText("atanr( " +valor1+")");
           atan = Math.atan(valor1);
           txtvisor_principal.setText(atan+"  ");
         break;
         }
       }
  
             
             
             
         }
    }
    private void boton_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cosActionPerformed
      funciones = "cos";
      Trigonometria();
    }//GEN-LAST:event_boton_cosActionPerformed

    private void boton_sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_sinActionPerformed
        funciones = "sin";
      Trigonometria();
    }//GEN-LAST:event_boton_sinActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        funciones = "atan";
      Trigonometria();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void boton_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_tanActionPerformed
        funciones = "tan";
      Trigonometria();
    }//GEN-LAST:event_boton_tanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  funciones = "acos";
      Trigonometria();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        funciones = "asin";
      Trigonometria();
    }//GEN-LAST:event_jButton8ActionPerformed
//boton que devuelveel valor Pi
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       txtvisor_previo.setText("PI");
        txtvisor_principal.setText(Math.PI +" ");
       
    }//GEN-LAST:event_jButton3ActionPerformed
//boton que eleva a x a la-1
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       valor1 = Double.parseDouble(txtvisor_principal.getText());
       txtvisor_previo.setText(valor1 + "  ^-1  ");
       txtvisor_principal.setText(Math.pow(valor1, -1) + " " );
       
    }//GEN-LAST:event_jButton9ActionPerformed
//Botón que eleva un numero a x Potencia
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
      inicio = true;
      valor1 = Double.parseDouble(txtvisor_principal.getText());
      txtvisor_previo.setText(valor1 + "^");
      tipoOperaciones = "potencia";
        operacion1 = false;
        igual=true;
        
    
    }//GEN-LAST:event_jButton15ActionPerformed
//Boton que saca la raiz x de un numero
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       inicio = true;
       valor1=Double.parseDouble(txtvisor_principal.getText());
       txtvisor_previo.setText(valor1+ "yroot");
       tipoOperaciones = "raizx";
       operacion1 = false;
       igual = true;
               
               
    }//GEN-LAST:event_jButton10ActionPerformed
//boton que elva z x al cubo
    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
       valor1 =Double.parseDouble(txtvisor_principal.getText());
       txtvisor_previo.setText("cube" +valor1+")");
       txtvisor_principal.setText(Math.pow(valor1, 3)+" ");
    }//GEN-LAST:event_jButton16ActionPerformed
 //boton que devuelve el valor de e
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtvisor_previo.setText("E");
        txtvisor_principal.setText(Math.E +" ");
    }//GEN-LAST:event_jButton4ActionPerformed
//boton que devuelve el factorial de un numero
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       a = 1;
       valor1 =Double.parseDouble(txtvisor_principal.getText());
        txtvisor_previo.setText("fact" +valor1+")");
        for(b = 1; b <= valor1; b++){
            a = a*b;
              }
        txtvisor_principal.setText(a +" ");
      

    }//GEN-LAST:event_jButton5ActionPerformed
//boton de la raiz cucubica
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
   valor1 =Double.parseDouble(txtvisor_principal.getText());
   a = 1;
   b = 3;
   c = a/b;
   txtvisor_previo.setText("cuberot("+ valor1 + ")");
   txtvisor_principal.setText(Math.pow(valor1,c) + " ");
   
   
   
   
    }//GEN-LAST:event_jButton11ActionPerformed
//boton eleva a x al cuadrado
    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
valor1 =Double.parseDouble(txtvisor_principal.getText());
txtvisor_previo.setText("aqr("+ valor1 + ")");
txtvisor_principal.setText(Math.pow(valor1,2)+ " ");
    }//GEN-LAST:event_jButton17ActionPerformed
//boton que eleva 10 a la potencia
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        valor1 =Double.parseDouble(txtvisor_principal.getText());
        txtvisor_previo.setText("powten("+ valor1 + ")");
        txtvisor_principal.setText(Math.pow(10,valor1)+ " ");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
    valor1 =Double.parseDouble(txtvisor_principal.getText());
     txtvisor_principal.setText(Math.exp(valor1) + " ");
    }//GEN-LAST:event_jButton12ActionPerformed
//boton del logaritmo neperiano
    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
       valor1 =Double.parseDouble(txtvisor_principal.getText());
        txtvisor_previo.setText("log("+ valor1 + ")");
        txtvisor_principal.setText(Math.log(valor1) + " ");
    }//GEN-LAST:event_jButton18ActionPerformed
 //boton con la funcion MC
    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        memoria =0;
     Label2_Memoría.setVisible(false);
    }//GEN-LAST:event_jButton19ActionPerformed
 //boton con la funcion MR
    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
      txtvisor_principal.setText(memoria +" ");
    }//GEN-LAST:event_jButton25ActionPerformed
 //boton con la funcion MS
    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
   memoria = Double.parseDouble(txtvisor_principal.getText());
    Label2_Memoría.setVisible(true);
    }//GEN-LAST:event_jButton31ActionPerformed
//boton con la funcion M+
    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
       memoria = memoria+Double.parseDouble(txtvisor_principal.getText());
       Label2_Memoría.setVisible(true);
    }//GEN-LAST:event_jButton37ActionPerformed
//boton con la funcion M-
    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
  memoria = memoria-Double.parseDouble(txtvisor_principal.getText());
       Label2_Memoría.setVisible(true);
    }//GEN-LAST:event_jButton43ActionPerformed

    private void RadioButton_RadianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_RadianesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton_RadianesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaluladoraCientifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaluladoraCientifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaluladoraCientifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaluladoraCientifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaluladoraCientifica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label2_Memoría;
    private javax.swing.JRadioButton RadioButton_Radianes;
    private javax.swing.JRadioButton RadioButton_Sexages;
    private javax.swing.JButton boton_cos;
    private javax.swing.JButton boton_sin;
    private javax.swing.JButton boton_tan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonN0;
    private javax.swing.JButton jButtonN1;
    private javax.swing.JButton jButtonN2;
    private javax.swing.JButton jButtonN3;
    private javax.swing.JButton jButtonN4;
    private javax.swing.JButton jButtonN5;
    private javax.swing.JButton jButtonN6;
    private javax.swing.JButton jButtonN7;
    private javax.swing.JButton jButtonN8;
    private javax.swing.JButton jButtonN9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtvisor_previo;
    private javax.swing.JTextField txtvisor_principal;
    // End of variables declaration//GEN-END:variables

    private static class Label_memoria {

        private static void setVisible(boolean igual) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public Label_memoria() {
            
        }
    }
}
